### ISSUE TITLE
WINDOWS BINARIES?

### ISSUE THREAD

**Issue by kokolino2** [joylazari/m3u8-dl#1]
Hello, 'joylazari'!

Would you mind, creating Windows binaries, occasionally?
Good luck!!!!!

Peter

**Comment by joylazari** [comment]
Check out the [run.cmd](https://github.com/joylazari/m3u8-dl/blob/main/bin/run.cmd) script from the bin directory.

**Comment by kokolino2** [comment]
Hello, again!

Thank You, "joylazari"!!!

But I can not see any binaries (for Windows operating system), there!? I ask you if there will be any executables which can be run (started) in Windows XP 64-bit version!? Or in Windows 7!?

Have a nice day!!!!!

Peter

**Comment by joylazari** [comment]
Hi Peter, 
To run this tool you don't need a binary.
Check out this guide on how to run a `*.cmd` script in windows shell: https://ss64.com/nt/syntax-run.html
